### ISSUE TITLE
Tool not running

### ISSUE THREAD

**Issue by gauth123** [prydin/vrops-export#22]
Hi Team,
I have downloaded this tool on windows and i was able to export data from vRops for 2 times. when i run the command for 3rd time it is not working.
getting below error,
C:\vropsexport\vrops-export-2.1-SNAPSHOT\bin>exporttool.bat -d ..\samples\vrops_
VMstats_aiml_001.yaml -u admin -p xxxxxxxx -H https://xxxxxxxxxx -s
"2019-05-11 00:00:00" -e "2019-05-20 00:00:00" -o D:\vRops\May11to19.csv
Exception in thread "main" org.apache.http.HttpException: HTTP Error: 401 Reason
: 401
        at net.virtualviking.vropsexport.Client.checkResponse(Client.java:179)
        at net.virtualviking.vropsexport.Client.postJsonReturnStream(Client.java
:156)
        at net.virtualviking.vropsexport.Client.<init>(Client.java:105)
        at net.virtualviking.vropsexport.Exporter.<init>(Exporter.java:118)
        at net.virtualviking.vropsexport.Main.createExporter(Main.java:192)
        at net.virtualviking.vropsexport.Main.main(Main.java:169)

**Comment by gauth123** [comment]
I see that after sometime it starts working , So when data is captured of very large size then it taes time to run the next export.

**Comment by prydin** [comment]
It could be that the login session expires while running a large export. A workaround would be to break it up into smaller batches.
